Vagrant.configure("2") do |config|
  config.vm.define "server01" do |server01|

    server01.vm.box = "centos/7"
    server01.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = "1"
    end
    server01.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  #config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provision "shell", path: "provision.sh"
    end
end
